#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pleroma"
name = "Pleroma"
description.en = "Federated social networking server built on open protocols"
description.fr = "Serveur de réseautage social fédéré basé sur des protocoles ouverts"

version = "2.8.0~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0-only"
website = "https://pleroma.social/"
admindoc = "https://docs.pleroma.social/"
code = "https://git.pleroma.social/pleroma/pleroma/"
cpe = "cpe:2.3:a:kpherox:pleroma"
fund = "https://liberapay.com/Pleroma-euro/"

[integration]
yunohost = ">= 12.0.0"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = false

ldap = true

sso = false

disk = "200M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.instance_name]
    ask.en = "Choose a name for your Pleroma instance"
    ask.fr = "Choisissez un nom pour votre instance Pleroma"
    type = "string"
    example = "My_Pleroma"
    default = "My_Pleroma"

    [install.registration]
    ask.en = "Should registration be open to users who do not have a YunoHost account on the system?"
    ask.fr = "L'inscription doit-elle être ouverte aux utilisateurs qui n'ont pas de compte YunoHost sur le système ?"
    type = "boolean"
    default = false

    [install.cache]
    ask.en = "Enable media-cache for your instance"
    ask.fr = "Activer le cache média pour votre instance"
    type = "boolean"
    default = true

    [install.size]
    ask.en = "Select the cache size. If you did not enabled media-cache in above option then this option will have no effect"
    ask.fr = "Sélectionner la taille du cache. Si vous n'avez pas activé le cache média ci-dessus, cette option n'aura aucun effet"
    type = "select"
    choices = ["2g", "5g", "10g", "20g", "40g", "80g"]
    default = "5g"

[resources]
    [resources.sources.main]
    amd64.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/283011/artifacts/download"
    amd64.sha256 = "31440d91e7448cd3912144638ea7c59300d45c2fecfad24f0cf9c8ea91058ce0"

    armhf.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/282573/artifacts/download"
    armhf.sha256 = "fdb6e7103a1de055102c30158f1153be468d424a1c9b713dd2571deb2aa20f4f"

    arm64.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/283015/artifacts/download"
    arm64.sha256 = "ffb9f5c56531076ca14bb23c25d7e78547fb4ef37c7eafd81740bfde966358a8"

    format = "zip"
    extract = true

    [resources.system_user]
    # This will provision/deprovision a unix system user

    [resources.install_dir]
    # This will create/remove the install dir as /var/www/$app
    # and store the corresponding setting $install_dir

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir
    subdirs = [
        "uploads", "static", "static/emoji",
    ]

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question (public=visitors, private=all_users)
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    main.default = 8095

    [resources.apt]
    # This will automatically install/uninstall the following apt packages
    # and implicitly define the $phpversion setting as 8.0 (if phpX.Y-foobar dependencies are listed)
    packages = [
        "curl",
        "unzip",
        "libncurses5",
        "imagemagick",
        "ffmpeg",
        "exiftool",
        "libimage-exiftool-perl",
        "postgresql",
        "postgresql-contrib",
        "libmagic-dev",
        "libimage-exiftool-perl",
        "libvips"
    ]

    [resources.database]
    # This will automatically provision/deprovison a DB and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    type = "postgresql"
