#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "pleroma"
name = "Pleroma"
description.en = "Federated social networking server built on open protocols"
description.fr = "Serveur de réseautage social fédéré basé sur des protocoles ouverts"

version = "2.6.2~ynh1"

maintainers = ["Anmol Sharma", "yalh76"]

[upstream]
license = "AGPL-3.0-only"
website = "https://pleroma.social/"
admindoc = "https://docs.pleroma.social/"
code = "https://git.pleroma.social/pleroma/pleroma/"
cpe = "cpe:2.3:a:kpherox:pleroma"
fund = "https://liberapay.com/Pleroma-euro/"

[integration]
yunohost = ">=11.2"
architectures = ["amd64", "armhf", "arm64"]
multi_instance = false
ldap = true
sso = false
disk = "200M"
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.name]
    ask.en = "Choose a name for your Pleroma instance"
    ask.fr = "Choisissez un nom pour votre instance Pleroma"
    type = "string"
    example = "My_Pleroma"
    default = "My_Pleroma"

    [install.registration]
    ask.en = "Should registration be open to users who do not have a YunoHost account on the system?"
    ask.fr = "L'inscription doit-elle être ouverte aux utilisateurs qui n'ont pas de compte YunoHost sur le système ?"
    type = "boolean"
    default = false

    [install.cache]
    ask.en = "Enable media-cache for your instance"
    ask.fr = "Activer le cache média pour votre instance"
    type = "boolean"
    default = true

    [install.size]
    ask.en = "Select the cache size. If you did not enabled media-cache in above option then this option will have no effect"
    ask.fr = "Sélectionner la taille du cache. Si vous n'avez pas activé le cache média ci-dessus, cette option n'aura aucun effet"
    type = "select"
    choices = ["2g", "5g", "10g", "20g", "40g", "80g"]
    default = "5g"

[resources]
    [resources.sources.main]
    amd64.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/256761/artifacts/download"
    amd64.sha256 = "4408be4d30c669a58589f3f0e5754c4f17f6a99d012c801204aacdcda4f1c9ef"

    armhf.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/256788/artifacts/download"
    armhf.sha256 = "ceff4df89f53654cfac3aafb685d0df2977a3073133ca7a472e92ebb349a58f1"

    arm64.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/256765/artifacts/download"
    arm64.sha256 = "eb38fddc449a0b47191d284671af3f1fe229b4d31b420cb8478f615006bd8757"

    format = "zip"
    extract = true

    # Those assets are to make autoupdate work, but are dummy artifacts, because
    # We need to find the actual artifacts from the CI jobs...
    autoupdate.strategy = "latest_gitlab_release"
    autoupdate.asset.amd64 = "source.tar.gz"
    autoupdate.asset.arm64 = "source.tar.gz"
    autoupdate.asset.armhf = "source.tar.gz"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [
        "uploads", "static", "static/emoji",
    ]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8095

    [resources.apt]
    packages = [
        "curl",
        "unzip",
        "libncurses5",
        "imagemagick",
        "ffmpeg",
        "exiftool",
        "libimage-exiftool-perl",
        "postgresql",
        "postgresql-contrib",
    ]

    [resources.database]
    type = "postgresql"
