packaging_format = 2

id = "pleroma"
name = "Pleroma"
description.en = "Federated social networking server built on open protocols"
description.fr = "Serveur de réseautage social fédéré basé sur des protocoles ouverts"

version = "2.5.2~ynh1"

maintainers = ["Anmol Sharma", "yalh76"]

[upstream]
license = "AGPL-3.0-only"
website = "https://pleroma.social/"
admindoc = "https://docs.pleroma.social/"
code = "https://git.pleroma.social/pleroma/pleroma/"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.3.1.8"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = false
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "password"

    [install.name]
    ask.en = "Choose a name for your Pleroma instance"
    ask.fr = "Choisissez un nom pour votre instance Pleroma"
    type = "string"
    example = "My_Pleroma"
    default = "My_Pleroma"

    [install.registration]
    ask.en = "Should registration be open to users who do not have a YunoHost account on the system?"
    ask.fr = "L'inscription doit-elle être ouverte aux utilisateurs qui n'ont pas de compte YunoHost sur le système ?"
    type = "boolean"
    default = false

    [install.cache]
    ask.en = "Enable media-cache for your instance"
    ask.fr = "Activer le cache média pour votre instance"
    type = "boolean"
    default = true

    [install.size]
    ask.en = "Select the cache size. If you did not enabled media-cache in above option then this option will have no effect"
    ask.fr = "Sélectionner la taille du cache. Si vous n'avez pas activé le cache média ci-dessus, cette option n'aura aucun effet"
    type = "string"
    choices = ["2g", "5g", "10g", "20g", "40g", "80g"]
    default = "5g"

[resources]
        [resources.sources.main]
        arm64.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/234437/artifacts/download?file_type=archive"
        arm64.sha256 = "2e2622a7a50284573fbb3dc66f0510c03d19403ab1e23d6b5dce7bddc11fca95"
        amd64.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/234433/artifacts/download?file_type=archive"
        amd64.sha256 = "8ef0bea62671d39e60f9e08d13109a4c332c552a1f855184063353987d46c84a"
        armhf.url = "https://git.pleroma.social/pleroma/pleroma/-/jobs/234449/artifacts/download?file_type=archive"
        armhf.sha256 = "abab2ad69704b999dbe1b995ce12aabc8069d9620ca332ecc621b20826d6db97"


    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.database]
    type = "postgresql"
