test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
		arg.name = "My_Pleroma"
		arg.registration = 0
		arg.cache = 1
		arg.size = "5g"
