test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------
    
		args.name = "My_Pleroma"
		args.registration = 0
		args.cache = 1
		args.size = "5g"
