#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	### Remove this function if there's nothing to clean before calling the remove script.
	true
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

final_path=$(ynh_app_setting_get $app final_path)
domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get "$app" psql_db)
cache=$(ynh_app_setting_get "$app" cache)

# Stop Pleroma for backup 
yunohost service stop "$app"

#=================================================
# STANDARD BACKUP STEPS
#=================================================
# BACKUP THE APP MAIN DIR
#=================================================

ynh_backup "$final_path"

#=================================================
# BACKUP THE NGINX CONFIGURATION
#=================================================

ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf"

if [ $cache -eq 1 ]
then
	ynh_backup "/etc/nginx/conf.d/$app-cache.conf"
fi

#=================================================
# BACKUP THE PHP-FPM CONFIGURATION
#=================================================

#ynh_backup "/etc/php5/fpm/pool.d/$app.conf"

#=================================================
# BACKUP THE POSTGRESQL DATABASE
#=================================================

ynh_psql_dump_db "$db_name" > db.sql
#ynh_backup "db.sql"

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP LOGROTATE
#=================================================

ynh_backup "/etc/logrotate.d/$app"

#=================================================
# BACKUP SYSTEMD
#=================================================

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# BACKUP A CRON FILE
#=================================================

#ynh_backup "/etc/cron.d/$app"

#=================================================
# START SERVICE
#=================================================

yunohost service start $app