#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status "$app" >/dev/null; then
    ynh_script_progression "Removing $app service integration..."
    yunohost service remove "$app"
fi

# Remove the dedicated systemd config
ynh_systemctl --service=$app --action="stop" --log_path=systemd --wait_until="Stopped $app"
pkill -u "$app" || true
ynh_config_remove_systemd

# Remove the dedicated NGINX config
ynh_config_remove_nginx
ynh_safe_rm "/etc/nginx/conf.d/$app-cache.conf"

ynh_safe_rm "/etc/$app"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
