#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_systemd_action
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info "Load settings"

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
port=$(ynh_app_setting_get $app port)
db_name=$(ynh_app_setting_get $app db_name)
final_path=$(ynh_app_setting_get $app final_path)
cache=$(ynh_app_setting_get "$app" cache)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
if yunohost service status | grep -q $app
then
	ynh_print_info "Remove $app service"
	yunohost service remove $app
fi

#=================================================
# START SERVICE
#=================================================

ynh_systemd_action --action=stop --service_name=$app

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_print_info "Stop and remove the service"

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE THE POSTGRESQL DATABASE
#=================================================
ynh_print_info "Remove the postgresql database"

ynh_psql_execute_as_root "\connect $db_name 
SELECT pg_terminate_backend (pg_stat_activity.pid) FROM pg_stat_activity WHERE pg_stat_activity.datname = '$db_name';"

# Remove a database if it exists, along with the associated user
ynh_psql_remove_db "$db_name" "$app"

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_print_info "Remove dependencies"

# Remove metapackage and its dependencies
ynh_remove_app_dependencies
ynh_secure_remove "/etc/apt/sources.list.d/erlang-solutions.list"

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_print_info "Remove app main directory"

# Remove the app directory securely
ynh_secure_remove "$final_path"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_print_info "Remove nginx configuration"

# Remove the dedicated nginx config
ynh_remove_nginx_config
ynh_secure_remove "/etc/nginx/conf.d/$app-cache.conf"

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================
ynh_print_info "Remove php-fpm configuration"

# Remove the dedicated php-fpm config
#ynh_remove_fpm_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_print_info "Remove logrotate configuration"

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# CLOSE A PORT
#=================================================
ynh_print_info "Close ports"

if yunohost firewall list | grep -q "\- $port$"
then
	echo "Close port $port" >&2
	yunohost firewall disallow TCP $port 2>&1
fi

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE THE CRON FILE
#=================================================

# Remove a cron file
#ynh_secure_remove "/etc/cron.d/$app"

# Remove a directory securely
ynh_secure_remove "/etc/$app/"

# Remove the log files
ynh_secure_remove "/var/log/$app/"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_print_info "Remove the dedicated user"

# Delete a system user
ynh_system_user_delete $app

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Deletion completed"
